name: Push file to GitHub repository

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Push file
        run: |
          git add .
          git commit -m "Added new file"
          git push origin main
